import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { z } from "zod";
import { authOptions } from "@/lib/auth";
import { db } from "@/lib/db";
import { evaluateMockInterviewAnswer } from "@/lib/mock-interview-evaluator";
import { getMockInterviewAccessContextByInterview } from "@/lib/mock-interview-access";
import { getQuestionByRoundAndIndex, getRoundDefinition, interpolatePlaceholders } from "@/lib/mock-interview-questions";

const answerSchema = z.object({
  roundNumber: z.number().int().min(1).max(10),
  questionNumber: z.number().int().min(1),
  question: z.string().min(1),
  answer: z.string().min(1),
  isFollowUp: z.boolean().optional(),
  isAutoGenerated: z.boolean().optional(),
  parentExchangeId: z.string().optional(),
});

type QuestionBankRound = {
  roundNumber: number;
  roundName: string;
  questions: Array<{ question: string }>;
};

async function getQuestionBankMap() {
  const rows = await db.mockInterviewQuestion.findMany({
    where: { isActive: true },
    orderBy: [{ roundNumber: "asc" }, { orderIndex: "asc" }, { createdAt: "asc" }],
    select: {
      roundNumber: true,
      roundName: true,
      questionText: true,
    },
  });

  const map = new Map<number, QuestionBankRound>();
  for (const row of rows) {
    if (!map.has(row.roundNumber)) {
      map.set(row.roundNumber, {
        roundNumber: row.roundNumber,
        roundName: row.roundName,
        questions: [],
      });
    }
    map.get(row.roundNumber)!.questions.push({ question: row.questionText });
  }

  return map;
}

function getRoundDefinitionForAnswer(roundNumber: number, bankMap: Map<number, QuestionBankRound>) {
  return bankMap.get(roundNumber) || getRoundDefinition(roundNumber);
}

function getQuestionForAnswer(roundNumber: number, questionNumber: number, bankMap: Map<number, QuestionBankRound>) {
  const round = bankMap.get(roundNumber);
  if (round) return round.questions[questionNumber - 1] || null;
  return getQuestionByRoundAndIndex(roundNumber, questionNumber);
}

function nextQuestionPointer(currentRoundNumber: number, currentQuestionNumber: number, bankMap: Map<number, QuestionBankRound>) {
  const currentRound = getRoundDefinitionForAnswer(currentRoundNumber, bankMap);
  if (!currentRound) return null;

  if (currentQuestionNumber < currentRound.questions.length) {
    return { roundNumber: currentRoundNumber, questionNumber: currentQuestionNumber + 1 };
  }

  const nextRound = getRoundDefinitionForAnswer(currentRoundNumber + 1, bankMap);
  if (!nextRound) return null;
  return { roundNumber: nextRound.roundNumber, questionNumber: 1 };
}

export async function POST(req: NextRequest, { params }: { params: { id: string } }) {
  const session = await getServerSession(authOptions);
  const access = await getMockInterviewAccessContextByInterview(session, params.id);

  if (!access) return NextResponse.json({ error: "Interview not found or access denied" }, { status: 404 });
  if (access.actor.roleName !== "STUDENT" && access.actor.roleName !== "ADMIN") {
    return NextResponse.json({ error: "Only students can answer the interview" }, { status: 403 });
  }

  try {
    const payload = answerSchema.parse(await req.json());

    const interview = await db.mockInterview.findUnique({
      where: { id: params.id },
      include: {
        application: {
          select: {
            course: { select: { name: true, university: { select: { name: true, country: true } } } },
          },
        },
      },
    });

    if (!interview) return NextResponse.json({ error: "Interview not found" }, { status: 404 });
    if (interview.status === "COMPLETED") return NextResponse.json({ error: "Interview already completed" }, { status: 400 });

    const questionBankMap = await getQuestionBankMap();
    const roundDef = getRoundDefinitionForAnswer(payload.roundNumber, questionBankMap);
    if (!roundDef) return NextResponse.json({ error: "Invalid round" }, { status: 400 });

    const round = await db.mockInterviewRound.upsert({
      where: {
        mockInterviewId_roundNumber: {
          mockInterviewId: interview.id,
          roundNumber: payload.roundNumber,
        },
      },
      create: {
        mockInterviewId: interview.id,
        roundNumber: payload.roundNumber,
        roundName: roundDef.roundName,
      },
      update: {},
    });

    const previousRows = await db.mockInterviewExchange.findMany({
      where: {
        round: {
          mockInterviewId: interview.id,
        },
      },
      include: {
        round: {
          select: {
            roundNumber: true,
          },
        },
      },
      orderBy: [{ round: { roundNumber: "asc" } }, { questionNumber: "asc" }, { askedAt: "asc" }],
    });

    const evalResult = await evaluateMockInterviewAnswer({
      universityAboutText: interview.universityAboutText,
      coursePageText: interview.sampleQuestionsText,
      extractedOfferData: {
        university: interview.extractedUniversity,
        course: interview.extractedCourse,
        duration: interview.extractedDuration,
        tuitionFee: interview.extractedTuitionFee,
        startDate: interview.extractedStartDate,
      },
      sampleQuestionsText: interview.sampleQuestionsText,
      customInstructions: interview.customInstructions,
      previousExchanges: previousRows.map((row) => ({
        question: row.question,
        answer: row.answer,
        roundNumber: row.round.roundNumber,
      })),
      question: payload.question,
      answer: payload.answer,
    });

    await db.mockInterviewExchange.create({
      data: {
        roundId: round.id,
        questionNumber: payload.questionNumber,
        question: payload.question,
        answer: payload.answer,
        aiEvaluation: evalResult.evaluation,
        score: evalResult.score,
        flags: evalResult.flags,
        isFollowUp: payload.isFollowUp ?? false,
        isAutoGenerated: payload.isAutoGenerated ?? false,
        parentExchangeId: payload.parentExchangeId || null,
        answeredAt: new Date(),
      },
    });

    const roundRows = await db.mockInterviewExchange.findMany({
      where: { roundId: round.id },
      select: { score: true },
    });

    const roundScores = roundRows.map((r) => r.score).filter((score): score is number => typeof score === "number");
    const roundAverage = roundScores.length ? roundScores.reduce((sum, s) => sum + s, 0) / roundScores.length : null;

    await db.mockInterviewRound.update({
      where: { id: round.id },
      data: {
        questionsAsked: roundRows.length,
        score: roundAverage,
      },
    });

    const vars = {
      universityName: interview.extractedUniversity || interview.application.course.university.name,
      courseName: interview.extractedCourse || interview.application.course.name,
      country: interview.application.course.university.country,
      cityCountry: interview.application.course.university.country,
    };

    // Only generate a follow-up if this was NOT already a follow-up answer
    // (prevents infinite loops where Claude keeps requesting follow-ups)
    if (!payload.isFollowUp && evalResult.followUpNeeded && evalResult.followUpQuestion) {
      return NextResponse.json({
        data: {
          next: {
            roundNumber: payload.roundNumber,
            questionNumber: payload.questionNumber,
            question: evalResult.followUpQuestion,
            isFollowUp: true,
            isAutoGenerated: true,
            parentQuestionNumber: payload.questionNumber,
          },
          evaluation: evalResult,
          done: false,
        },
      });
    }

    const pointer = nextQuestionPointer(payload.roundNumber, payload.questionNumber, questionBankMap);
    if (!pointer) {
      return NextResponse.json({
        data: {
          next: null,
          evaluation: evalResult,
          done: true,
        },
      });
    }

    const nextQuestion = getQuestionForAnswer(pointer.roundNumber, pointer.questionNumber, questionBankMap);
    if (!nextQuestion) {
      return NextResponse.json({
        data: {
          next: null,
          evaluation: evalResult,
          done: true,
        },
      });
    }

    if (pointer.roundNumber !== payload.roundNumber) {
      const nextRound = getRoundDefinitionForAnswer(pointer.roundNumber, questionBankMap)!;
      await db.mockInterviewRound.upsert({
        where: {
          mockInterviewId_roundNumber: {
            mockInterviewId: interview.id,
            roundNumber: pointer.roundNumber,
          },
        },
        create: {
          mockInterviewId: interview.id,
          roundNumber: pointer.roundNumber,
          roundName: nextRound.roundName,
        },
        update: {},
      });

      await db.mockInterviewRound.update({
        where: { id: round.id },
        data: {
          completedAt: new Date(),
        },
      });
    }

    return NextResponse.json({
      data: {
        next: {
          roundNumber: pointer.roundNumber,
          questionNumber: pointer.questionNumber,
          question: interpolatePlaceholders(nextQuestion.question, vars),
          isFollowUp: false,
          isAutoGenerated: false,
          roundName: getRoundDefinitionForAnswer(pointer.roundNumber, questionBankMap)?.roundName,
        },
        evaluation: evalResult,
        done: false,
      },
    });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json({ error: error.issues[0]?.message || "Invalid payload" }, { status: 400 });
    }

    console.error("[/api/student/mock-interviews/[id]/answer POST]", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
