import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { db } from "@/lib/db";
import {
  buildTranscript,
  calculateOverallWeightedScore,
  generateMockInterviewReportWithClaude,
} from "@/lib/mock-interview-evaluator";
import { getMockInterviewAccessContextByInterview } from "@/lib/mock-interview-access";
import { createMockInterviewReportPdf, uploadMockInterviewReportPdf } from "@/lib/mock-interview-report-pdf";
import { notifyMockInterviewCompleted } from "@/lib/mock-interview-notifications";

export async function POST(_req: Request, { params }: { params: { id: string } }) {
  const session = await getServerSession(authOptions);
  const access = await getMockInterviewAccessContextByInterview(session, params.id);

  if (!access) return NextResponse.json({ error: "Interview not found or access denied" }, { status: 404 });
  if (access.actor.roleName !== "STUDENT" && access.actor.roleName !== "ADMIN") {
    return NextResponse.json({ error: "Only students can complete the interview" }, { status: 403 });
  }

  const interview = await db.mockInterview.findUnique({
    where: { id: params.id },
    include: {
      student: {
        select: {
          id: true,
          userId: true,
          firstName: true,
          lastName: true,
          email: true,
          nationality: true,
          subAgentId: true,
          subAgentStaffId: true,
        },
      },
      application: {
        select: {
          id: true,
          course: { select: { name: true, university: { select: { name: true } } } },
        },
      },
      rounds: {
        include: {
          exchanges: {
            orderBy: [{ questionNumber: "asc" }, { askedAt: "asc" }],
          },
        },
        orderBy: { roundNumber: "asc" },
      },
      report: true,
    },
  });

  if (!interview) return NextResponse.json({ error: "Interview not found" }, { status: 404 });
  if (interview.status === "COMPLETED" && interview.report) {
    return NextResponse.json({ data: { interviewId: interview.id, alreadyCompleted: true } });
  }

  const roundScores = interview.rounds.map((r) => ({
    roundNumber: r.roundNumber,
    roundName: r.roundName,
    score: r.score,
  }));

  const overallScore = calculateOverallWeightedScore(roundScores);
  const inconsistencies = interview.rounds
    .flatMap((r) => r.exchanges)
    .flatMap((x) => (Array.isArray(x.flags) ? x.flags : []))
    .filter((f): f is string => typeof f === "string" && /inconsisten/i.test(f));

  const transcript = buildTranscript(
    interview.rounds.flatMap((round) =>
      round.exchanges.map((exchange) => ({
        roundNumber: round.roundNumber,
        roundName: round.roundName,
        questionNumber: exchange.questionNumber,
        question: exchange.question,
        answer: exchange.answer,
        score: exchange.score,
        isAutoGenerated: exchange.isAutoGenerated,
        isFollowUp: exchange.isFollowUp,
        flags: exchange.flags,
      })),
    ),
  );

  const reportPayload = await generateMockInterviewReportWithClaude({
    studentName: `${interview.student.firstName} ${interview.student.lastName}`.trim(),
    interviewType: interview.interviewType,
    passingScore: interview.passingScore,
    overallScore,
    roundScores,
    inconsistencies,
    transcript,
  });

  let reportDocumentUrl: string | null = null;
  try {
    const pdfBytes = await createMockInterviewReportPdf({
      title: "Mock Interview Evaluation Report",
      studentName: `${interview.student.firstName} ${interview.student.lastName}`.trim(),
      nationality: interview.student.nationality,
      universityName: interview.application.course.university.name,
      courseName: interview.application.course.name,
      interviewType: interview.interviewType,
      dateCompleted: new Date(),
      overallScore: reportPayload.overallScore,
      recommendation: reportPayload.recommendation,
      roundScores,
      strengths: reportPayload.strengths,
      areasToImprove: reportPayload.areasToImprove,
      detailedFeedback: reportPayload.detailedFeedback,
      transcript,
    });

    reportDocumentUrl = await uploadMockInterviewReportPdf(
      `mock-interview-${interview.student.id}-${Date.now()}.pdf`,
      pdfBytes,
    );
  } catch (error) {
    console.error("Mock interview report PDF generation/upload failed", error);
  }

  const completedAt = new Date();

  await db.$transaction(async (tx) => {
    await tx.mockInterview.update({
      where: { id: interview.id },
      data: {
        status: "COMPLETED",
        completedAt,
        overallScore: reportPayload.overallScore,
        recommendation: reportPayload.recommendation,
        reportDocumentUrl,
      },
    });

    await tx.mockInterviewRound.updateMany({
      where: { mockInterviewId: interview.id, completedAt: null },
      data: { completedAt },
    });

    if (interview.report) {
      await tx.mockInterviewReport.update({
        where: { mockInterviewId: interview.id },
        data: {
          overallScore: reportPayload.overallScore,
          isPassed: reportPayload.isPassed,
          recommendation: reportPayload.recommendation,
          round1Score: roundScores.find((r) => r.roundNumber === 1)?.score ?? null,
          round2Score: roundScores.find((r) => r.roundNumber === 2)?.score ?? null,
          round3Score: roundScores.find((r) => r.roundNumber === 3)?.score ?? null,
          round4Score: roundScores.find((r) => r.roundNumber === 4)?.score ?? null,
          round5Score: roundScores.find((r) => r.roundNumber === 5)?.score ?? null,
          round6Score: roundScores.find((r) => r.roundNumber === 6)?.score ?? null,
          round7Score: roundScores.find((r) => r.roundNumber === 7)?.score ?? null,
          round8Score: roundScores.find((r) => r.roundNumber === 8)?.score ?? null,
          round9Score: roundScores.find((r) => r.roundNumber === 9)?.score ?? null,
          round10Score: roundScores.find((r) => r.roundNumber === 10)?.score ?? null,
          strengths: reportPayload.strengths,
          areasToImprove: reportPayload.areasToImprove,
          inconsistenciesFound: reportPayload.inconsistenciesFound,
          detailedFeedback: reportPayload.detailedFeedback,
          fullTranscript: transcript,
          generatedAt: completedAt,
          notificationsSentAt: completedAt,
        },
      });
    } else {
      await tx.mockInterviewReport.create({
        data: {
          mockInterviewId: interview.id,
          overallScore: reportPayload.overallScore,
          isPassed: reportPayload.isPassed,
          recommendation: reportPayload.recommendation,
          round1Score: roundScores.find((r) => r.roundNumber === 1)?.score ?? null,
          round2Score: roundScores.find((r) => r.roundNumber === 2)?.score ?? null,
          round3Score: roundScores.find((r) => r.roundNumber === 3)?.score ?? null,
          round4Score: roundScores.find((r) => r.roundNumber === 4)?.score ?? null,
          round5Score: roundScores.find((r) => r.roundNumber === 5)?.score ?? null,
          round6Score: roundScores.find((r) => r.roundNumber === 6)?.score ?? null,
          round7Score: roundScores.find((r) => r.roundNumber === 7)?.score ?? null,
          round8Score: roundScores.find((r) => r.roundNumber === 8)?.score ?? null,
          round9Score: roundScores.find((r) => r.roundNumber === 9)?.score ?? null,
          round10Score: roundScores.find((r) => r.roundNumber === 10)?.score ?? null,
          strengths: reportPayload.strengths,
          areasToImprove: reportPayload.areasToImprove,
          inconsistenciesFound: reportPayload.inconsistenciesFound,
          detailedFeedback: reportPayload.detailedFeedback,
          fullTranscript: transcript,
          generatedAt: completedAt,
          notificationsSentAt: completedAt,
        },
      });
    }

    if (reportDocumentUrl) {
      await tx.document.create({
        data: {
          studentId: interview.studentId,
          applicationId: interview.applicationId,
          type: "OTHER",
          fileName: `Mock Interview Report - ${new Date().toLocaleDateString("en-GB")}.pdf`,
          fileUrl: reportDocumentUrl,
          status: "VERIFIED",
        },
      });
    }
  });

  await notifyMockInterviewCompleted({
    interviewId: interview.id,
    studentId: interview.student.id,
    studentUserId: interview.student.userId,
    studentEmail: interview.student.email,
    studentName: `${interview.student.firstName} ${interview.student.lastName}`.trim(),
    universityName: interview.application.course.university.name,
    score: reportPayload.overallScore,
    recommendation: reportPayload.recommendation,
    assignedById: interview.assignedById,
    assignedByName: session?.user?.name || session?.user?.email || "Counsellor",
    subAgentId: interview.student.subAgentId,
    subAgentStaffId: interview.student.subAgentStaffId,
  }).catch(() => undefined);

  return NextResponse.json({
    data: {
      interviewId: interview.id,
      overallScore: reportPayload.overallScore,
      recommendation: reportPayload.recommendation,
      isPassed: reportPayload.isPassed,
      reportDocumentUrl,
    },
  });
}
