import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { db } from "@/lib/db";
import { getMockInterviewAccessContextByInterview } from "@/lib/mock-interview-access";
import { getRoundDefinition, interpolatePlaceholders } from "@/lib/mock-interview-questions";

async function getRoundFromBank(roundNumber: number) {
  const rows = await db.mockInterviewQuestion.findMany({
    where: { roundNumber, isActive: true },
    orderBy: [{ orderIndex: "asc" }, { createdAt: "asc" }],
    select: {
      questionText: true,
      roundName: true,
    },
  });

  if (rows.length > 0) {
    return {
      roundNumber,
      roundName: rows[0].roundName,
      questions: rows.map((row) => ({ question: row.questionText })),
    };
  }

  return getRoundDefinition(roundNumber);
}

export async function POST(_req: Request, { params }: { params: { id: string } }) {
  const session = await getServerSession(authOptions);
  const access = await getMockInterviewAccessContextByInterview(session, params.id);

  if (!access) return NextResponse.json({ error: "Interview not found or access denied" }, { status: 404 });
  if (access.actor.roleName !== "STUDENT" && access.actor.roleName !== "ADMIN") {
    return NextResponse.json({ error: "Only students can start the interview" }, { status: 403 });
  }

  const interview = await db.mockInterview.findUnique({
    where: { id: params.id },
    select: {
      id: true,
      status: true,
      extractedUniversity: true,
      extractedCourse: true,
      application: {
        select: {
          course: {
            select: {
              name: true,
              university: { select: { name: true, country: true } },
            },
          },
        },
      },
    },
  });

  if (!interview) return NextResponse.json({ error: "Interview not found" }, { status: 404 });
  if (interview.status === "COMPLETED") return NextResponse.json({ error: "Interview already completed" }, { status: 400 });

  const started = await db.mockInterview.update({
    where: { id: interview.id },
    data: {
      status: "IN_PROGRESS",
      startedAt: interview.status === "ASSIGNED" ? new Date() : undefined,
    },
  });

  const round1 = await getRoundFromBank(1);
  if (!round1) return NextResponse.json({ error: "Question bank not initialized" }, { status: 500 });

  await db.mockInterviewRound.upsert({
    where: {
      mockInterviewId_roundNumber: {
        mockInterviewId: interview.id,
        roundNumber: 1,
      },
    },
    create: {
      mockInterviewId: interview.id,
      roundNumber: 1,
      roundName: round1.roundName,
    },
    update: {},
  });

  const vars = {
    universityName: interview.extractedUniversity || interview.application.course.university.name,
    courseName: interview.extractedCourse || interview.application.course.name,
    country: interview.application.course.university.country,
    cityCountry: interview.application.course.university.country,
  };

  const first = round1.questions[0];

  return NextResponse.json({
    data: {
      interviewId: started.id,
      status: started.status,
      currentRound: 1,
      currentQuestionNumber: 1,
      roundName: round1.roundName,
      question: interpolatePlaceholders(first.question, vars),
      isFollowUp: false,
      isAutoGenerated: false,
      progressPct: 0,
    },
  });
}
