import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { z } from "zod";
import { authOptions } from "@/lib/auth";
import { db } from "@/lib/db";
import { getMockInterviewAccessContextByInterview } from "@/lib/mock-interview-access";
import { getQuestionByRoundAndIndex, getRoundDefinition, interpolatePlaceholders } from "@/lib/mock-interview-questions";

const skipSchema = z.object({
  roundNumber: z.number().int().min(1).max(10),
  questionNumber: z.number().int().min(1),
  question: z.string().min(1),
  isFollowUp: z.boolean().optional(),
});

type QuestionBankRound = {
  roundNumber: number;
  roundName: string;
  questions: Array<{ question: string }>;
};

async function getQuestionBankMap() {
  const rows = await db.mockInterviewQuestion.findMany({
    where: { isActive: true },
    orderBy: [{ roundNumber: "asc" }, { orderIndex: "asc" }, { createdAt: "asc" }],
    select: { roundNumber: true, roundName: true, questionText: true },
  });

  const map = new Map<number, QuestionBankRound>();
  for (const row of rows) {
    if (!map.has(row.roundNumber)) {
      map.set(row.roundNumber, { roundNumber: row.roundNumber, roundName: row.roundName, questions: [] });
    }
    map.get(row.roundNumber)!.questions.push({ question: row.questionText });
  }
  return map;
}

function getRoundDef(roundNumber: number, bankMap: Map<number, QuestionBankRound>) {
  return bankMap.get(roundNumber) || getRoundDefinition(roundNumber);
}

function getQuestion(roundNumber: number, questionNumber: number, bankMap: Map<number, QuestionBankRound>) {
  const round = bankMap.get(roundNumber);
  if (round) return round.questions[questionNumber - 1] || null;
  return getQuestionByRoundAndIndex(roundNumber, questionNumber);
}

function nextPointer(roundNumber: number, questionNumber: number, bankMap: Map<number, QuestionBankRound>) {
  const round = getRoundDef(roundNumber, bankMap);
  if (!round) return null;
  // If this was a follow-up, advance the same question number to the NEXT question
  if (questionNumber < round.questions.length) {
    return { roundNumber, questionNumber: questionNumber + 1 };
  }
  const nextRound = getRoundDef(roundNumber + 1, bankMap);
  if (!nextRound) return null;
  return { roundNumber: nextRound.roundNumber, questionNumber: 1 };
}

export async function POST(req: NextRequest, { params }: { params: { id: string } }) {
  const session = await getServerSession(authOptions);
  const access = await getMockInterviewAccessContextByInterview(session, params.id);

  if (!access) return NextResponse.json({ error: "Interview not found or access denied" }, { status: 404 });
  if (access.actor.roleName !== "STUDENT") {
    return NextResponse.json({ error: "Only students can skip questions" }, { status: 403 });
  }

  try {
    const payload = skipSchema.parse(await req.json());

    const interview = await db.mockInterview.findUnique({
      where: { id: params.id },
      include: {
        application: {
          select: {
            course: { select: { name: true, university: { select: { name: true, country: true } } } },
          },
        },
      },
    });

    if (!interview) return NextResponse.json({ error: "Interview not found" }, { status: 404 });
    if (interview.status === "COMPLETED") return NextResponse.json({ error: "Interview already completed" }, { status: 400 });

    const questionBankMap = await getQuestionBankMap();
    const roundDef = getRoundDef(payload.roundNumber, questionBankMap);
    if (!roundDef) return NextResponse.json({ error: "Invalid round" }, { status: 400 });

    // Upsert the round record
    const round = await db.mockInterviewRound.upsert({
      where: {
        mockInterviewId_roundNumber: {
          mockInterviewId: interview.id,
          roundNumber: payload.roundNumber,
        },
      },
      create: {
        mockInterviewId: interview.id,
        roundNumber: payload.roundNumber,
        roundName: roundDef.roundName,
      },
      update: {},
    });

    // Record the skipped exchange with score 0 and SKIPPED flag
    await db.mockInterviewExchange.create({
      data: {
        roundId: round.id,
        questionNumber: payload.questionNumber,
        question: payload.question,
        answer: "[SKIPPED BY STUDENT]",
        aiEvaluation: "Student chose to skip this question.",
        score: 0,
        flags: ["SKIPPED"],
        isFollowUp: payload.isFollowUp ?? false,
        isAutoGenerated: false,
        answeredAt: new Date(),
      },
    });

    // Update round stats
    const roundRows = await db.mockInterviewExchange.findMany({
      where: { roundId: round.id },
      select: { score: true },
    });
    const scores = roundRows.map((r) => r.score).filter((s): s is number => typeof s === "number");
    const average = scores.length ? scores.reduce((a, b) => a + b, 0) / scores.length : null;
    await db.mockInterviewRound.update({
      where: { id: round.id },
      data: { questionsAsked: roundRows.length, score: average },
    });

    // For follow-up skips, advance past the parent question; for regular, just go next
    const pointer = nextPointer(payload.roundNumber, payload.questionNumber, questionBankMap);

    if (!pointer) {
      return NextResponse.json({ data: { next: null, done: true } });
    }

    const nextQuestion = getQuestion(pointer.roundNumber, pointer.questionNumber, questionBankMap);
    if (!nextQuestion) {
      return NextResponse.json({ data: { next: null, done: true } });
    }

    // Move to next round if needed
    if (pointer.roundNumber !== payload.roundNumber) {
      const nextRound = getRoundDef(pointer.roundNumber, questionBankMap)!;
      await db.mockInterviewRound.upsert({
        where: {
          mockInterviewId_roundNumber: {
            mockInterviewId: interview.id,
            roundNumber: pointer.roundNumber,
          },
        },
        create: {
          mockInterviewId: interview.id,
          roundNumber: pointer.roundNumber,
          roundName: nextRound.roundName,
        },
        update: {},
      });
      await db.mockInterviewRound.update({
        where: { id: round.id },
        data: { completedAt: new Date() },
      });
    }

    const vars = {
      universityName: interview.extractedUniversity || interview.application.course.university.name,
      courseName: interview.extractedCourse || interview.application.course.name,
      country: interview.application.course.university.country,
      cityCountry: interview.application.course.university.country,
    };

    return NextResponse.json({
      data: {
        next: {
          roundNumber: pointer.roundNumber,
          questionNumber: pointer.questionNumber,
          question: interpolatePlaceholders(nextQuestion.question, vars),
          isFollowUp: false,
          isAutoGenerated: false,
          roundName: getRoundDef(pointer.roundNumber, questionBankMap)?.roundName,
        },
        done: false,
      },
    });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json({ error: error.issues[0]?.message || "Invalid payload" }, { status: 400 });
    }
    console.error("[/api/student/mock-interviews/[id]/skip POST]", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
