"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, Loader2, Mic, MicOff, Send, SkipForward, X } from "lucide-react";
import { toast } from "sonner";

type SessionData = {
  interviewId: string;
  status: string;
  currentRound: number;
  currentQuestionNumber: number;
  roundName: string;
  question: string;
  isFollowUp: boolean;
  isAutoGenerated: boolean;
  progressPct: number;
};

type NextQuestion = {
  roundNumber: number;
  questionNumber: number;
  question: string;
  isFollowUp: boolean;
  isAutoGenerated: boolean;
  roundName?: string;
};

type AnswerResponse = {
  next: NextQuestion | null;
  evaluation: {
    score: number;
    evaluation: string;
    flags: string[];
    followUpNeeded: boolean;
  };
  done: boolean;
};

type SkipResponse = {
  next: NextQuestion | null;
  done: boolean;
};

type Props = {
  interviewId: string;
};

type SpeechRecognitionResultLike = {
  isFinal: boolean;
  0: { transcript: string };
};

type SpeechRecognitionEventLike = {
  resultIndex: number;
  results: ArrayLike<SpeechRecognitionResultLike>;
};

type SpeechRecognitionLike = {
  lang: string;
  continuous: boolean;
  interimResults: boolean;
  onresult: ((event: SpeechRecognitionEventLike) => void) | null;
  onerror: (() => void) | null;
  onend: (() => void) | null;
  start: () => void;
  stop: () => void;
};

type SpeechRecognitionCtor = new () => SpeechRecognitionLike;

declare global {
  interface Window {
    webkitSpeechRecognition?: SpeechRecognitionCtor;
    SpeechRecognition?: SpeechRecognitionCtor;
  }
}

export default function MockInterviewSession({ interviewId }: Props) {
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [skipping, setSkipping] = useState(false);
  const [stopping, setStopping] = useState(false);
  const [session, setSession] = useState<SessionData | null>(null);
  const [answer, setAnswer] = useState("");
  const [lastEval, setLastEval] = useState<AnswerResponse["evaluation"] | null>(null);
  const [micOn, setMicOn] = useState(false);
  const [showStopConfirm, setShowStopConfirm] = useState(false);
  const [skippedCount, setSkippedCount] = useState(0);
  const recognitionRef = useRef<SpeechRecognitionLike | null>(null);

  const progress = useMemo(() => {
    if (!session) return 0;
    // 10 rounds × ~7 questions avg = ~70 total; we track by round/question
    const completed = (session.currentRound - 1) * 7 + (session.currentQuestionNumber - 1);
    return Math.min(99, Math.round((completed / 70) * 100));
  }, [session]);

  useEffect(() => {
    let mounted = true;

    async function boot() {
      try {
        setLoading(true);
        const startRes = await fetch(`/api/student/mock-interviews/${interviewId}/start`, { method: "POST" });
        const startJson = (await startRes.json()) as { data?: SessionData; error?: string };
        if (!startRes.ok || !startJson.data) throw new Error(startJson.error || "Failed to start interview");
        if (!mounted) return;
        setSession(startJson.data);
      } catch (error) {
        toast.error(error instanceof Error ? error.message : "Failed to start interview");
      } finally {
        if (mounted) setLoading(false);
      }
    }

    void boot();

    return () => {
      mounted = false;
      if (recognitionRef.current) {
        recognitionRef.current.stop();
        recognitionRef.current = null;
      }
    };
  }, [interviewId]);

  function startVoiceInput() {
    const API = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (!API) {
      toast.error("Speech recognition is not supported in this browser.");
      return;
    }
    const recognition = new API();
    recognition.lang = "en-GB";
    recognition.continuous = true;
    recognition.interimResults = true;
    recognition.onresult = (event) => {
      let finalText = "";
      for (let i = event.resultIndex; i < event.results.length; i += 1) {
        const transcript = event.results[i][0]?.transcript || "";
        if (event.results[i].isFinal) finalText += `${transcript} `;
      }
      if (finalText.trim()) setAnswer((prev) => `${prev} ${finalText}`.trim());
    };
    recognition.onerror = () => { setMicOn(false); recognitionRef.current = null; };
    recognition.onend = () => { setMicOn(false); recognitionRef.current = null; };
    recognition.start();
    recognitionRef.current = recognition;
    setMicOn(true);
  }

  function stopVoiceInput() {
    recognitionRef.current?.stop();
    recognitionRef.current = null;
    setMicOn(false);
  }

  function applyNextQuestion(next: NextQuestion) {
    setSession((prev) => {
      if (!prev) return prev;
      return {
        ...prev,
        currentRound: next.roundNumber,
        currentQuestionNumber: next.questionNumber,
        roundName: next.roundName || prev.roundName,
        question: next.question,
        isFollowUp: next.isFollowUp,
        isAutoGenerated: next.isAutoGenerated,
      };
    });
    setAnswer("");
    setLastEval(null);
  }

  async function completeInterview() {
    setStopping(true);
    try {
      const res = await fetch(`/api/student/mock-interviews/${interviewId}/complete`, { method: "POST" });
      const json = (await res.json()) as { data?: { interviewId: string }; error?: string };
      if (!res.ok || !json.data) throw new Error(json.error || "Failed to complete interview");
      window.location.href = `/student/mock-interview/${interviewId}/report`;
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to complete interview");
      setStopping(false);
    }
  }

  async function submitAnswer() {
    if (!session || !answer.trim()) return;
    try {
      setSubmitting(true);
      const res = await fetch(`/api/student/mock-interviews/${interviewId}/answer`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          roundNumber: session.currentRound,
          questionNumber: session.currentQuestionNumber,
          question: session.question,
          answer: answer.trim(),
          isFollowUp: session.isFollowUp,
          isAutoGenerated: session.isAutoGenerated,
        }),
      });

      const json = (await res.json()) as { data?: AnswerResponse; error?: string };
      if (!res.ok || !json.data) throw new Error(json.error || "Failed to submit answer");

      setLastEval(json.data.evaluation);

      if (json.data.done || !json.data.next) {
        await completeInterview();
        return;
      }

      applyNextQuestion(json.data.next);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to submit answer");
    } finally {
      setSubmitting(false);
    }
  }

  async function skipQuestion() {
    if (!session) return;
    try {
      setSkipping(true);
      const res = await fetch(`/api/student/mock-interviews/${interviewId}/skip`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          roundNumber: session.currentRound,
          questionNumber: session.currentQuestionNumber,
          question: session.question,
          isFollowUp: session.isFollowUp,
        }),
      });

      const json = (await res.json()) as { data?: SkipResponse; error?: string };
      if (!res.ok || !json.data) throw new Error(json.error || "Failed to skip question");

      setSkippedCount((n) => n + 1);

      if (json.data.done || !json.data.next) {
        await completeInterview();
        return;
      }

      applyNextQuestion(json.data.next);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to skip question");
    } finally {
      setSkipping(false);
    }
  }

  if (loading || !session) {
    return (
      <div className="rounded-xl border border-slate-200 bg-white p-8 text-sm text-slate-600 text-center">
        <Loader2 className="mx-auto mb-2 h-6 w-6 animate-spin text-[#1B2A4A]" />
        Preparing your mock interview…
      </div>
    );
  }

  return (
    <section className="space-y-4">
      {/* Stop confirmation modal */}
      {showStopConfirm && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm">
          <div className="mx-4 w-full max-w-sm rounded-2xl bg-white p-6 shadow-2xl">
            <div className="flex items-start gap-3">
              <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-amber-500" />
              <div>
                <h2 className="text-sm font-bold text-slate-900">End interview early?</h2>
                <p className="mt-1 text-sm text-slate-600">
                  Your progress so far will be saved and a report will be generated from completed rounds.
                  {skippedCount > 0 && ` You have skipped ${skippedCount} question(s).`}
                </p>
              </div>
            </div>
            <div className="mt-4 flex gap-2">
              <button
                onClick={() => setShowStopConfirm(false)}
                className="flex-1 rounded-lg border border-slate-200 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50"
              >
                Continue Interview
              </button>
              <button
                onClick={() => { setShowStopConfirm(false); void completeInterview(); }}
                disabled={stopping}
                className="flex-1 rounded-lg bg-rose-600 py-2 text-sm font-semibold text-white hover:bg-rose-700 disabled:opacity-60"
              >
                {stopping ? <Loader2 className="mx-auto h-4 w-4 animate-spin" /> : "End & Generate Report"}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Progress bar */}
      <div className="rounded-xl border border-slate-200 bg-white p-4">
        <div className="mb-2 flex items-center justify-between text-xs text-slate-600">
          <span className="font-medium">
            Round {session.currentRound}/10 — {session.roundName}
            {session.isFollowUp && <span className="ml-2 rounded-full bg-amber-100 px-2 py-0.5 text-amber-700">Follow-up</span>}
          </span>
          <span>{progress}% complete</span>
        </div>
        <div className="h-2 w-full overflow-hidden rounded-full bg-slate-100">
          <div
            className="h-full transition-all duration-500"
            style={{ width: `${progress}%`, background: "linear-gradient(90deg, #1B2A4A, #F5A623)" }}
          />
        </div>
        {skippedCount > 0 && (
          <p className="mt-1.5 text-xs text-amber-600">{skippedCount} question(s) skipped — shown in your report</p>
        )}
      </div>

      {/* Question */}
      <div className="rounded-xl border border-slate-200 bg-white p-5">
        <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">
          Question {session.currentQuestionNumber}
        </p>
        <p className="mt-2 text-base font-medium text-slate-900">{session.question}</p>
      </div>

      {/* Answer */}
      <div className="rounded-xl border border-slate-200 bg-white p-5">
        <label className="mb-2 block text-sm font-semibold text-slate-700">Your answer</label>
        <textarea
          value={answer}
          onChange={(e) => setAnswer(e.target.value)}
          rows={6}
          className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none focus:border-[#1B2A4A] focus:ring-1 focus:ring-[#1B2A4A]/20"
          placeholder="Speak or type your answer here…"
        />

        <div className="mt-3 flex flex-wrap items-center gap-2">
          {/* Voice */}
          {!micOn ? (
            <button
              type="button"
              onClick={startVoiceInput}
              className="inline-flex items-center gap-1.5 rounded-lg border border-slate-300 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50"
            >
              <Mic className="h-4 w-4" /> Use Voice
            </button>
          ) : (
            <button
              type="button"
              onClick={stopVoiceInput}
              className="inline-flex items-center gap-1.5 rounded-lg border border-rose-300 px-3 py-2 text-xs font-semibold text-rose-700 hover:bg-rose-50"
            >
              <MicOff className="h-4 w-4" /> Stop Recording
            </button>
          )}

          {/* Submit */}
          <button
            type="button"
            onClick={() => void submitAnswer()}
            disabled={submitting || !answer.trim()}
            className="inline-flex items-center gap-1.5 rounded-lg px-4 py-2 text-xs font-semibold text-white disabled:opacity-60"
            style={{ background: "linear-gradient(135deg, #1B2A4A, #2f4f86)" }}
          >
            {submitting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}
            Submit Answer
          </button>

          {/* Skip */}
          <button
            type="button"
            onClick={() => void skipQuestion()}
            disabled={skipping || submitting}
            className="inline-flex items-center gap-1.5 rounded-lg border border-amber-300 bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-700 hover:bg-amber-100 disabled:opacity-60"
          >
            {skipping ? <Loader2 className="h-4 w-4 animate-spin" /> : <SkipForward className="h-4 w-4" />}
            Skip Question
          </button>

          {/* Stop */}
          <button
            type="button"
            onClick={() => setShowStopConfirm(true)}
            disabled={stopping || submitting}
            className="ml-auto inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-xs font-medium text-slate-500 hover:border-rose-300 hover:bg-rose-50 hover:text-rose-600 disabled:opacity-60"
          >
            <X className="h-3.5 w-3.5" /> End Interview
          </button>
        </div>
      </div>

      {/* Last evaluation feedback */}
      {lastEval && (
        <div className="rounded-xl border border-slate-200 bg-slate-50 p-4">
          <div className="flex items-center gap-2 mb-1">
            <span className="text-sm font-semibold text-slate-900">AI feedback</span>
            <span
              className="rounded-full px-2 py-0.5 text-xs font-bold"
              style={{
                background: lastEval.score >= 75 ? "#d1fae5" : lastEval.score >= 55 ? "#fef3c7" : "#fee2e2",
                color: lastEval.score >= 75 ? "#065f46" : lastEval.score >= 55 ? "#92400e" : "#991b1b",
              }}
            >
              {lastEval.score.toFixed(0)}%
            </span>
          </div>
          <p className="text-sm text-slate-700">{lastEval.evaluation}</p>
          {lastEval.flags.filter((f) => f !== "SKIPPED").length > 0 && (
            <p className="mt-1.5 text-xs text-amber-700">
              ⚠ {lastEval.flags.filter((f) => f !== "SKIPPED").join(" · ")}
            </p>
          )}
        </div>
      )}
    </section>
  );
}
