"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Loader2, Mic, MicOff, Send } from "lucide-react";
import { toast } from "sonner";

type SessionData = {
  interviewId: string;
  status: string;
  currentRound: number;
  currentQuestionNumber: number;
  roundName: string;
  question: string;
  isFollowUp: boolean;
  isAutoGenerated: boolean;
  progressPct: number;
};

type AnswerResponse = {
  next: {
    roundNumber: number;
    questionNumber: number;
    question: string;
    isFollowUp: boolean;
    isAutoGenerated: boolean;
    roundName?: string;
  } | null;
  evaluation: {
    score: number;
    evaluation: string;
    flags: string[];
    followUpNeeded: boolean;
  };
  done: boolean;
};

type Props = {
  interviewId: string;
};

type SpeechRecognitionResultLike = {
  isFinal: boolean;
  0: { transcript: string };
};

type SpeechRecognitionEventLike = {
  resultIndex: number;
  results: ArrayLike<SpeechRecognitionResultLike>;
};

type SpeechRecognitionLike = {
  lang: string;
  continuous: boolean;
  interimResults: boolean;
  onresult: ((event: SpeechRecognitionEventLike) => void) | null;
  onerror: (() => void) | null;
  onend: (() => void) | null;
  start: () => void;
  stop: () => void;
};

type SpeechRecognitionCtor = new () => SpeechRecognitionLike;

declare global {
  interface Window {
    webkitSpeechRecognition?: SpeechRecognitionCtor;
    SpeechRecognition?: SpeechRecognitionCtor;
  }
}

export default function MockInterviewSession({ interviewId }: Props) {
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [session, setSession] = useState<SessionData | null>(null);
  const [answer, setAnswer] = useState("");
  const [lastEval, setLastEval] = useState<AnswerResponse["evaluation"] | null>(null);
  const [micOn, setMicOn] = useState(false);
  const recognitionRef = useRef<SpeechRecognitionLike | null>(null);

  const progress = useMemo(() => {
    if (!session) return 0;
    const completed = (session.currentRound - 1) * 10 + (session.currentQuestionNumber - 1);
    return Math.min(100, Math.round((completed / 100) * 100));
  }, [session]);

  useEffect(() => {
    let mounted = true;

    async function boot() {
      try {
        setLoading(true);
        const startRes = await fetch(`/api/student/mock-interviews/${interviewId}/start`, { method: "POST" });
        const startJson = (await startRes.json()) as { data?: SessionData; error?: string };
        if (!startRes.ok || !startJson.data) throw new Error(startJson.error || "Failed to start interview");
        if (!mounted) return;
        setSession(startJson.data);
      } catch (error) {
        toast.error(error instanceof Error ? error.message : "Failed to start interview");
      } finally {
        if (mounted) setLoading(false);
      }
    }

    void boot();

    return () => {
      mounted = false;
      if (recognitionRef.current) {
        recognitionRef.current.stop();
        recognitionRef.current = null;
      }
    };
  }, [interviewId]);

  function startVoiceInput() {
    const API = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (!API) {
      toast.error("Speech recognition is not supported in this browser.");
      return;
    }

    const recognition = new API();
    recognition.lang = "en-GB";
    recognition.continuous = true;
    recognition.interimResults = true;

    recognition.onresult = (event) => {
      let finalText = "";
      for (let i = event.resultIndex; i < event.results.length; i += 1) {
        const transcript = event.results[i][0]?.transcript || "";
        if (event.results[i].isFinal) finalText += `${transcript} `;
      }
      if (finalText.trim()) {
        setAnswer((prev) => `${prev} ${finalText}`.trim());
      }
    };

    recognition.onerror = () => {
      setMicOn(false);
      recognitionRef.current = null;
    };

    recognition.onend = () => {
      setMicOn(false);
      recognitionRef.current = null;
    };

    recognition.start();
    recognitionRef.current = recognition;
    setMicOn(true);
  }

  function stopVoiceInput() {
    recognitionRef.current?.stop();
    recognitionRef.current = null;
    setMicOn(false);
  }

  async function submitAnswer() {
    if (!session || !answer.trim()) return;

    try {
      setSubmitting(true);
      const res = await fetch(`/api/student/mock-interviews/${interviewId}/answer`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          roundNumber: session.currentRound,
          questionNumber: session.currentQuestionNumber,
          question: session.question,
          answer: answer.trim(),
          isFollowUp: session.isFollowUp,
          isAutoGenerated: session.isAutoGenerated,
        }),
      });

      const json = (await res.json()) as { data?: AnswerResponse; error?: string };
      if (!res.ok || !json.data) throw new Error(json.error || "Failed to submit answer");

      setLastEval(json.data.evaluation);
      setAnswer("");

      if (json.data.done || !json.data.next) {
        const doneRes = await fetch(`/api/student/mock-interviews/${interviewId}/complete`, { method: "POST" });
        const doneJson = (await doneRes.json()) as { data?: { interviewId: string }; error?: string };
        if (!doneRes.ok || !doneJson.data) throw new Error(doneJson.error || "Failed to complete interview");
        window.location.href = `/student/mock-interview/${interviewId}/report`;
        return;
      }

      setSession((prev) => {
        if (!prev) return prev;
        return {
          ...prev,
          currentRound: json.data!.next!.roundNumber,
          currentQuestionNumber: json.data!.next!.questionNumber,
          roundName: json.data!.next!.roundName || prev.roundName,
          question: json.data!.next!.question,
          isFollowUp: json.data!.next!.isFollowUp,
          isAutoGenerated: json.data!.next!.isAutoGenerated,
        };
      });
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to submit answer");
    } finally {
      setSubmitting(false);
    }
  }

  if (loading || !session) {
    return (
      <div className="rounded-xl border border-slate-200 bg-white p-6 text-sm text-slate-600">
        <Loader2 className="mr-2 inline h-4 w-4 animate-spin" /> Preparing your mock interview...
      </div>
    );
  }

  return (
    <section className="space-y-4">
      <div className="rounded-xl border border-slate-200 bg-white p-4">
        <div className="mb-2 flex items-center justify-between text-xs text-slate-600">
          <span>Round {session.currentRound}/10 • Question {session.currentQuestionNumber}</span>
          <span>{progress}%</span>
        </div>
        <div className="h-2 w-full overflow-hidden rounded-full bg-slate-100">
          <div className="h-full bg-blue-600" style={{ width: `${progress}%` }} />
        </div>
      </div>

      <div className="rounded-xl border border-slate-200 bg-white p-5">
        <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{session.roundName}</p>
        <p className="mt-2 text-base font-medium text-slate-900">{session.question}</p>
      </div>

      <div className="rounded-xl border border-slate-200 bg-white p-5">
        <label className="mb-2 block text-sm font-semibold text-slate-700">Your answer (text transcript only)</label>
        <textarea
          value={answer}
          onChange={(event) => setAnswer(event.target.value)}
          rows={6}
          className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none focus:border-blue-500"
          placeholder="Speak or type your answer here..."
        />

        <div className="mt-3 flex flex-wrap items-center gap-2">
          {!micOn ? (
            <button
              type="button"
              onClick={startVoiceInput}
              className="inline-flex items-center gap-2 rounded-lg border border-slate-300 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50"
            >
              <Mic className="h-4 w-4" /> Use Voice Input
            </button>
          ) : (
            <button
              type="button"
              onClick={stopVoiceInput}
              className="inline-flex items-center gap-2 rounded-lg border border-rose-300 px-3 py-2 text-xs font-semibold text-rose-700 hover:bg-rose-50"
            >
              <MicOff className="h-4 w-4" /> Stop Voice Input
            </button>
          )}

          <button
            type="button"
            onClick={() => void submitAnswer()}
              disabled={submitting || !answer.trim()}
            className="inline-flex items-center gap-2 rounded-lg bg-[#1E3A5F] px-4 py-2 text-xs font-semibold text-white hover:opacity-95 disabled:opacity-60"
          >
            {submitting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />} Submit Answer
          </button>
        </div>
      </div>

      {lastEval && (
        <div className="rounded-xl border border-slate-200 bg-slate-50 p-4">
          <p className="text-sm font-semibold text-slate-900">AI feedback on last answer: {lastEval.score.toFixed(2)}%</p>
          <p className="mt-1 text-sm text-slate-700">{lastEval.evaluation}</p>
          {lastEval.flags.length > 0 && <p className="mt-2 text-xs text-amber-700">Flags: {lastEval.flags.join(", ")}</p>}
        </div>
      )}
    </section>
  );
}
