-- CreateEnum
CREATE TYPE "MockInterviewType" AS ENUM ('PRE_CAS_UNIVERSITY', 'UK_VISA', 'US_VISA', 'CANADA_STUDY_PERMIT', 'AUSTRALIA_STUDENT_VISA', 'GENERAL_PREPARATION');

-- CreateEnum
CREATE TYPE "MockInterviewStatus" AS ENUM ('ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'EXPIRED');

-- CreateTable
CREATE TABLE "MockInterview" (
    "id" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "studentId" TEXT NOT NULL,
    "assignedById" TEXT NOT NULL,
    "interviewType" "MockInterviewType" NOT NULL,
    "status" "MockInterviewStatus" NOT NULL DEFAULT 'ASSIGNED',
    "assignedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "startedAt" TIMESTAMP(3),
    "completedAt" TIMESTAMP(3),
    "offerLetterUrl" TEXT,
    "courseUrl" TEXT,
    "universityAboutUrl" TEXT,
    "universityAboutText" TEXT,
    "sampleQuestionsUrl" TEXT,
    "sampleQuestionsText" TEXT,
    "extractedUniversity" TEXT,
    "extractedCourse" TEXT,
    "extractedDuration" TEXT,
    "extractedTuitionFee" TEXT,
    "extractedStartDate" TEXT,
    "customQuestions" JSONB,
    "customInstructions" TEXT,
    "passingScore" INTEGER NOT NULL DEFAULT 80,
    "overallScore" DOUBLE PRECISION,
    "recommendation" TEXT,
    "attemptNumber" INTEGER NOT NULL DEFAULT 1,
    "reportDocumentUrl" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "MockInterview_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MockInterviewRound" (
    "id" TEXT NOT NULL,
    "mockInterviewId" TEXT NOT NULL,
    "roundNumber" INTEGER NOT NULL,
    "roundName" TEXT NOT NULL,
    "score" DOUBLE PRECISION,
    "questionsAsked" INTEGER NOT NULL DEFAULT 0,
    "completedAt" TIMESTAMP(3),

    CONSTRAINT "MockInterviewRound_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MockInterviewExchange" (
    "id" TEXT NOT NULL,
    "roundId" TEXT NOT NULL,
    "questionNumber" INTEGER NOT NULL,
    "question" TEXT NOT NULL,
    "answer" TEXT,
    "aiEvaluation" TEXT,
    "score" DOUBLE PRECISION,
    "flags" JSONB,
    "isFollowUp" BOOLEAN NOT NULL DEFAULT false,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "parentExchangeId" TEXT,
    "askedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "answeredAt" TIMESTAMP(3),

    CONSTRAINT "MockInterviewExchange_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MockInterviewReport" (
    "id" TEXT NOT NULL,
    "mockInterviewId" TEXT NOT NULL,
    "overallScore" DOUBLE PRECISION NOT NULL,
    "isPassed" BOOLEAN NOT NULL,
    "recommendation" TEXT NOT NULL,
    "round1Score" DOUBLE PRECISION,
    "round2Score" DOUBLE PRECISION,
    "round3Score" DOUBLE PRECISION,
    "round4Score" DOUBLE PRECISION,
    "round5Score" DOUBLE PRECISION,
    "round6Score" DOUBLE PRECISION,
    "round7Score" DOUBLE PRECISION,
    "round8Score" DOUBLE PRECISION,
    "round9Score" DOUBLE PRECISION,
    "round10Score" DOUBLE PRECISION,
    "strengths" JSONB NOT NULL,
    "areasToImprove" JSONB NOT NULL,
    "inconsistenciesFound" JSONB,
    "detailedFeedback" TEXT NOT NULL,
    "fullTranscript" TEXT NOT NULL,
    "generatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "notificationsSentAt" TIMESTAMP(3),

    CONSTRAINT "MockInterviewReport_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MockInterviewQuestion" (
    "id" TEXT NOT NULL,
    "roundNumber" INTEGER NOT NULL,
    "roundName" TEXT NOT NULL,
    "questionText" TEXT NOT NULL,
    "followUpQuestion" TEXT,
    "evaluationCriteria" TEXT,
    "redFlags" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "orderIndex" INTEGER NOT NULL DEFAULT 0,
    "createdBy" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "MockInterviewQuestion_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "MockInterview_applicationId_idx" ON "MockInterview"("applicationId");

-- CreateIndex
CREATE INDEX "MockInterview_studentId_idx" ON "MockInterview"("studentId");

-- CreateIndex
CREATE INDEX "MockInterview_assignedById_idx" ON "MockInterview"("assignedById");

-- CreateIndex
CREATE INDEX "MockInterview_status_idx" ON "MockInterview"("status");

-- CreateIndex
CREATE INDEX "MockInterview_interviewType_idx" ON "MockInterview"("interviewType");

-- CreateIndex
CREATE INDEX "MockInterview_assignedAt_idx" ON "MockInterview"("assignedAt");

-- CreateIndex
CREATE INDEX "MockInterviewRound_mockInterviewId_idx" ON "MockInterviewRound"("mockInterviewId");

-- CreateIndex
CREATE INDEX "MockInterviewRound_roundNumber_idx" ON "MockInterviewRound"("roundNumber");

-- CreateIndex
CREATE UNIQUE INDEX "MockInterviewRound_mockInterviewId_roundNumber_key" ON "MockInterviewRound"("mockInterviewId", "roundNumber");

-- CreateIndex
CREATE INDEX "MockInterviewExchange_roundId_idx" ON "MockInterviewExchange"("roundId");

-- CreateIndex
CREATE INDEX "MockInterviewExchange_questionNumber_idx" ON "MockInterviewExchange"("questionNumber");

-- CreateIndex
CREATE UNIQUE INDEX "MockInterviewReport_mockInterviewId_key" ON "MockInterviewReport"("mockInterviewId");

-- CreateIndex
CREATE INDEX "MockInterviewQuestion_roundNumber_idx" ON "MockInterviewQuestion"("roundNumber");

-- CreateIndex
CREATE INDEX "MockInterviewQuestion_isActive_idx" ON "MockInterviewQuestion"("isActive");

-- CreateIndex
CREATE INDEX "MockInterviewQuestion_orderIndex_idx" ON "MockInterviewQuestion"("orderIndex");

-- AddForeignKey
ALTER TABLE "MockInterview" ADD CONSTRAINT "MockInterview_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MockInterview" ADD CONSTRAINT "MockInterview_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MockInterview" ADD CONSTRAINT "MockInterview_assignedById_fkey" FOREIGN KEY ("assignedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MockInterviewRound" ADD CONSTRAINT "MockInterviewRound_mockInterviewId_fkey" FOREIGN KEY ("mockInterviewId") REFERENCES "MockInterview"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MockInterviewExchange" ADD CONSTRAINT "MockInterviewExchange_roundId_fkey" FOREIGN KEY ("roundId") REFERENCES "MockInterviewRound"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MockInterviewReport" ADD CONSTRAINT "MockInterviewReport_mockInterviewId_fkey" FOREIGN KEY ("mockInterviewId") REFERENCES "MockInterview"("id") ON DELETE CASCADE ON UPDATE CASCADE;
